# Generated by Django 4.2.1 on 2023-10-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temppurchase',
            name='invoice',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
