# Generated by Django 4.2.1 on 2023-10-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry_app', '0003_alter_temppurchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='temsale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
