# Generated by Django 4.2.1 on 2023-10-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventry_app', '0004_temsale_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temsale',
            name='total_amount',
        ),
    ]
