# Generated by Django 4.2.1 on 2023-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry_app', '0006_alter_temsale_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temsale',
            name='invoice_no',
            field=models.CharField(max_length=50),
        ),
    ]
