# Generated by Django 4.2.1 on 2023-10-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry_app', '0008_alter_purchase_datetime_alter_temppurchase_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateField(verbose_name='date'),
        ),
    ]
